/******************************************************************************
*
* Copyright (C) Chaoyong Zhou
* Email: bgnvendor@163.com
* QQ: 2796796
*
*******************************************************************************/
#ifdef __cplusplus
extern "C"{
#endif/*__cplusplus*/

#ifndef _CROUTINE_INC
#define _CROUTINE_INC


#endif/*_CROUTINE_INC*/

#ifdef __cplusplus
}
#endif/*__cplusplus*/

