/******************************************************************************
*
* Copyright (C) Chaoyong Zhou
* Email: bgnvendor@163.com
* QQ: 2796796
*
*******************************************************************************/
#ifndef _DENY_REASON_INC_
#define _DENY_REASON_INC_
#define DENY_REASON_NONE_BASE               ((UINT32)(       0))
#define DENY_REASON_NONE_END                ((UINT32)(       1))
#endif/*_DENY_REASON_INC_*/
