/******************************************************************************
*
* Copyright (C) Chaoyong Zhou
* Email: bgnvendor@163.com
* QQ: 2796796
*
*******************************************************************************/
#ifndef _DENY_REASON_INC_
#define _DENY_REASON_INC_
#define DENY_REASON_NONE_BASE               ((UINT32)(       0))
#define DENY_REASON_CLOOPBACK_0001          ((UINT32)(       1))
#define DENY_REASON_CLOOPBACK_0002          ((UINT32)(       2))
#define DENY_REASON_CLOOPBACK_0003          ((UINT32)(       3))
#define DENY_REASON_CLOOPBACK_0004          ((UINT32)(       4))
#define DENY_REASON_CMIAOPAI_0001           ((UINT32)(       5))
#define DENY_REASON_CMIAOPAI_0002           ((UINT32)(       6))
#define DENY_REASON_CMIAOPAI_0003           ((UINT32)(       7))
#define DENY_REASON_CMIAOPAI_0004           ((UINT32)(       8))
#define DENY_REASON_CMIAOPAI_0005           ((UINT32)(       9))
#define DENY_REASON_CMIAOPAI_0006           ((UINT32)(      10))
#define DENY_REASON_CMIAOPAI_0007           ((UINT32)(      11))
#define DENY_REASON_CMIAOPAI_0008           ((UINT32)(      12))
#define DENY_REASON_CMIAOPAI_0009           ((UINT32)(      13))
#define DENY_REASON_CMIAOPAI_0010           ((UINT32)(      14))
#define DENY_REASON_CMIAOPAI_0011           ((UINT32)(      15))
#define DENY_REASON_CMIAOPAI_0012           ((UINT32)(      16))
#define DENY_REASON_CMIAOPAI_0013           ((UINT32)(      17))
#define DENY_REASON_CMIAOPAI_0014           ((UINT32)(      18))
#define DENY_REASON_CMIAOPAI_0015           ((UINT32)(      19))
#define DENY_REASON_CMIAOPAI_0016           ((UINT32)(      20))
#define DENY_REASON_CMIAOPAI_0017           ((UINT32)(      21))
#define DENY_REASON_CMIAOPAI_0018           ((UINT32)(      22))
#define DENY_REASON_CMIAOPAI_0019           ((UINT32)(      23))
#define DENY_REASON_CMIAOPAI_0020           ((UINT32)(      24))
#define DENY_REASON_NONE_END                ((UINT32)(      25))
#endif/*_DENY_REASON_INC_*/
