/******************************************************************************
*
* Copyright (C) Chaoyong Zhou
* Email: bgnvendor@163.com
* QQ: 2796796
*
*******************************************************************************/
#ifndef _SEC_MACRO_INC
#define _SEC_MACRO_INC
#define SEC_0000_CPGRB                      ((UINT32)(      0)) /*cpgrb                           */
#define SEC_0001_COROUTINE                  ((UINT32)(      1)) /*coroutine                       */
#define SEC_0002_CBTIMER                    ((UINT32)(      2)) /*cbtimer                         */
#define SEC_0003_CCONSOLE                   ((UINT32)(      3)) /*cconsole                        */
#define SEC_0004_CCODE                      ((UINT32)(      4)) /*ccode                           */
#define SEC_0005_CROUTER                    ((UINT32)(      5)) /*crouter                         */
#define SEC_0006_LIST                       ((UINT32)(      6)) /*list                            */
#define SEC_0007_CQUEUE                     ((UINT32)(      7)) /*cqueue                          */
#define SEC_0008_CSTRKV                     ((UINT32)(      8)) /*cstrkv                          */
#define SEC_0009_CUNIXPACKET                ((UINT32)(      9)) /*cunixpacket                     */
#define SEC_0010_API                        ((UINT32)(     10)) /*api                             */
#define SEC_0011_CDEVICE                    ((UINT32)(     11)) /*cdevice                         */
#define SEC_0012_CBASE64CODE                ((UINT32)(     12)) /*cbase64code                     */
#define SEC_0013_CMISC                      ((UINT32)(     13)) /*cmisc                           */
#define SEC_0014_CSIG                       ((UINT32)(     14)) /*csig                            */
#define SEC_0015_TASK                       ((UINT32)(     15)) /*task                            */
#define SEC_0016_CTHREAD                    ((UINT32)(     16)) /*cthread                         */
#define SEC_0017_CARRAY                     ((UINT32)(     17)) /*carray                          */
#define SEC_0018_CRANGE                     ((UINT32)(     18)) /*crange                          */
#define SEC_0019_TASKCFG                    ((UINT32)(     19)) /*taskcfg                         */
#define SEC_0020_CMAP                       ((UINT32)(     20)) /*cmap                            */
#define SEC_0021_CTDNSNPRB                  ((UINT32)(     21)) /*ctdnsnprb                       */
#define SEC_0022_CTDNSNP                    ((UINT32)(     22)) /*ctdnsnp                         */
#define SEC_0023_CMON                       ((UINT32)(     23)) /*cmon                            */
#define SEC_0024_CFUSES                     ((UINT32)(     24)) /*cfuses                          */
#define SEC_0025_CSESSION                   ((UINT32)(     25)) /*csession                        */
#define SEC_0026_CTDNS                      ((UINT32)(     26)) /*ctdns                           */
#define SEC_0027_IPV4POOL                   ((UINT32)(     27)) /*ipv4pool                        */
#define SEC_0028_CMD5                       ((UINT32)(     28)) /*cmd5                            */
#define SEC_0029_CSEM                       ((UINT32)(     29)) /*csem                            */
#define SEC_0030_CTDNSNPMGR                 ((UINT32)(     30)) /*ctdnsnpmgr                      */
#define SEC_0031_CFUSEC                     ((UINT32)(     31)) /*cfusec                          */
#define SEC_0032_CDSK                       ((UINT32)(     32)) /*cdsk                            */
#define SEC_0033_CRBUFF                     ((UINT32)(     33)) /*crbuff                          */
#define SEC_0034_CFUSED                     ((UINT32)(     34)) /*cfused                          */
#define SEC_0035_CMPIE                      ((UINT32)(     35)) /*cmpie                           */
#define SEC_0036_CFUSEO                     ((UINT32)(     36)) /*cfuseo                          */
#define SEC_0037_CSBUFF                     ((UINT32)(     37)) /*csbuff                          */
#define SEC_0038_CRB                        ((UINT32)(     38)) /*crb                             */
#define SEC_0039_CTDNSSVRB                  ((UINT32)(     39)) /*ctdnssvrb                       */
#define SEC_0040_CBLOOM                     ((UINT32)(     40)) /*cbloom                          */
#define SEC_0041_CPGD                       ((UINT32)(     41)) /*cpgd                            */
#define SEC_0042_CDBGCODE                   ((UINT32)(     42)) /*cdbgcode                        */
#define SEC_0043_CDETECT                    ((UINT32)(     43)) /*cdetect                         */
#define SEC_0044_CLIST                      ((UINT32)(     44)) /*clist                           */
#define SEC_0045_CDETECTHTTP                ((UINT32)(     45)) /*cdetecthttp                     */
#define SEC_0046_CXML                       ((UINT32)(     46)) /*cxml                            */
#define SEC_0047_DEBUG                      ((UINT32)(     47)) /*debug                           */
#define SEC_0048_CTDNSHTTP                  ((UINT32)(     48)) /*ctdnshttp                       */
#define SEC_0049_CXFS_FUSEC                 ((UINT32)(     49)) /*cxfsfusec                       */
#define SEC_0050_CCONHASH                   ((UINT32)(     50)) /*cconhash                        */
#define SEC_0051_CTDNSSV                    ((UINT32)(     51)) /*ctdnssv                         */
#define SEC_0052_CPARACFG                   ((UINT32)(     52)) /*cparacfg                        */
#define SEC_0053_CSOCKET                    ((UINT32)(     53)) /*csocket                         */
#define SEC_0054_CNGX_HTTP                  ((UINT32)(     54)) /*cngx_http                       */
#define SEC_0055_CTDNSSVMGR                 ((UINT32)(     55)) /*ctdnssvmgr                      */
#define SEC_0056_CNGX_HTTPS                 ((UINT32)(     56)) /*cngx_https                      */
#define SEC_0057_TASKCFGCHK                 ((UINT32)(     57)) /*taskcfgchk                      */
#define SEC_0058_CSDISC                     ((UINT32)(     58)) /*csdisc                          */
#define SEC_0059_CP2P                       ((UINT32)(     59)) /*cp2p                            */
#define SEC_0060_CAGENT                     ((UINT32)(     60)) /*cagent                          */
#define SEC_0061_CHASHDB                    ((UINT32)(     61)) /*chashdb                         */
#define SEC_0062_CROUTINE                   ((UINT32)(     62)) /*croutine                        */
#define SEC_0063_CPING                      ((UINT32)(     63)) /*cping                           */
#define SEC_0064_CHASHALGO                  ((UINT32)(     64)) /*chashalgo                       */
#define SEC_0065_CDNSCACHE                  ((UINT32)(     65)) /*cdnscache                       */
#define SEC_0066_MM                         ((UINT32)(     66)) /*mm                              */
#define SEC_0067_CSTACK                     ((UINT32)(     67)) /*cstack                          */
#define SEC_0068_CP2PHTTP                   ((UINT32)(     68)) /*cp2phttp                        */
#define SEC_0069_CFILE                      ((UINT32)(     69)) /*cfile                           */
#define SEC_0070_CDETECTN                   ((UINT32)(     70)) /*cdetectn                        */
#define SEC_0071_CXFS_FUSEO                 ((UINT32)(     71)) /*cxfsfuseo                       */
#define SEC_0072_CEPOLL                     ((UINT32)(     72)) /*cepoll                          */
#define SEC_0073_CEVENTFD                   ((UINT32)(     73)) /*ceventfd                        */
#define SEC_0074_CPGV                       ((UINT32)(     74)) /*cpgv                            */
#define SEC_0075_CTIMER                     ((UINT32)(     75)) /*ctimer                          */
#define SEC_0076_XXXXXXXXX                  ((UINT32)(     76)) /*-- obsolete --                  */
#define SEC_0077_CSYS                       ((UINT32)(     77)) /*csys                            */
#define SEC_0078_PRINT                      ((UINT32)(     78)) /*print                           */
#define SEC_0079_TBD                        ((UINT32)(     79)) /*tbd                             */
#define SEC_0080_CVECTOR                    ((UINT32)(     80)) /*cvector                         */
#define SEC_0081_XXXXXX                     ((UINT32)(     81)) /*-- obsolete --                  */
#define SEC_0082_CSTRING                    ((UINT32)(     82)) /*cstring                         */
#define SEC_0083_CMUTEX                     ((UINT32)(     83)) /*cmutex                          */
#define SEC_0084_DHCP                       ((UINT32)(     84)) /*dhcp                            */
#define SEC_0085_CPROC                      ((UINT32)(     85)) /*cproc                           */
#define SEC_0086_CLOAD                      ((UINT32)(     86)) /*cload                           */
#define SEC_0087_CRBBASE                    ((UINT32)(     87)) /*crbbase                         */
#define SEC_0088_TCNODE                     ((UINT32)(     88)) /*tcnode                          */
#define SEC_0089_CBITMAP                    ((UINT32)(     89)) /*cbitmap                         */
#define SEC_0090_CSYSCFG                    ((UINT32)(     90)) /*csyscfg                         */
#define SEC_0091_CBC                        ((UINT32)(     91)) /*cbc                             */
#define SEC_0092_CMIAOPAI                   ((UINT32)(     92)) /*cmiaopai                        */
#define SEC_0093_CAIO                       ((UINT32)(     93)) /*caio                            */
#define SEC_0094_KBUFF                      ((UINT32)(     94)) /*kbuff                           */
#define SEC_0095_RANK                       ((UINT32)(     95)) /*rank                            */
#define SEC_0096_CMCPGRB                    ((UINT32)(     96)) /*cmcpgrb                         */
#define SEC_0097_CTIMEOUT                   ((UINT32)(     97)) /*ctimeout                        */
#define SEC_0098_CMCPGB                     ((UINT32)(     98)) /*cmcpgb                          */
#define SEC_0099_CHUNK                      ((UINT32)(     99)) /*chunk                           */
#define SEC_0100_XXXXXXXX                   ((UINT32)(    100)) /*-- obsolete --                  */
#define SEC_0101_CBYTES                     ((UINT32)(    101)) /*cbytes                          */
#define SEC_0102_CMCPGD                     ((UINT32)(    102)) /*cmcpgd                          */
#define SEC_0103_CHASHNODE                  ((UINT32)(    103)) /*chashnode                       */
#define SEC_0104_LOG                        ((UINT32)(    104)) /*log                             */
#define SEC_0105_CMCPGV                     ((UINT32)(    105)) /*cmcpgv                          */
#define SEC_0106_CINDEX                     ((UINT32)(    106)) /*cindex                          */
#define SEC_0107_CCOREDUMPER                ((UINT32)(    107)) /*ccoredumper                     */
#define SEC_0108_MOD                        ((UINT32)(    108)) /*mod                             */
#define SEC_0109_SHA256                     ((UINT32)(    109)) /*sha256                          */
#define SEC_0110_CMCDN                      ((UINT32)(    110)) /*cmcdn                           */
#define SEC_0111_CMCNP                      ((UINT32)(    111)) /*cmcnp                           */
#define SEC_0112_CSRV                       ((UINT32)(    112)) /*csrv                            */
#define SEC_0113_CMCNPRB                    ((UINT32)(    113)) /*cmcnprb                         */
#define SEC_0114_CMCNPQUE                   ((UINT32)(    114)) /*cmcnpque                        */
#define SEC_0115_CHASHVEC                   ((UINT32)(    115)) /*chashvec                        */
#define SEC_0116_CMCNPDEL                   ((UINT32)(    116)) /*cmcnpdel                        */
#define SEC_0117_SUPER                      ((UINT32)(    117)) /*super                           */
#define SEC_0118_CMC                        ((UINT32)(    118)) /*cmc                             */
#define SEC_0119_REAL                       ((UINT32)(    119)) /*real                            */
#define SEC_0120_CBYTECODE                  ((UINT32)(    120)) /*cbytecode                       */
#define SEC_0121_TASKS                      ((UINT32)(    121)) /*tasks                           */
#define SEC_0122_CPGB                       ((UINT32)(    122)) /*cpgb                            */
#define SEC_0123_CREG                       ((UINT32)(    123)) /*creg                            */
#define SEC_0124_HTTP                       ((UINT32)(    124)) /*http                            */
#define SEC_0125_CAMD                       ((UINT32)(    125)) /*camd                            */
#define SEC_0126_CBUFFER                    ((UINT32)(    126)) /*cbuffer                         */
#define SEC_0127_CLOOPBACK                  ((UINT32)(    127)) /*cloopback                       */
#define SEC_0128_CSET                       ((UINT32)(    128)) /*cset                            */
#define SEC_0129_CDCNP                      ((UINT32)(    129)) /*cdcnp                           */
#define SEC_0130_BTREE                      ((UINT32)(    130)) /*btree                           */
#define SEC_0131_DB                         ((UINT32)(    131)) /*db                              */
#define SEC_0132_RAW                        ((UINT32)(    132)) /*raw                             */
#define SEC_0133_KEYVALUE                   ((UINT32)(    133)) /*keyvalue                        */
#define SEC_0134_POSLIST                    ((UINT32)(    134)) /*poslist                         */
#define SEC_0135_CDCNPDEL                   ((UINT32)(    135)) /*cdcnpdel                        */
#define SEC_0136_GM                         ((UINT32)(    136)) /*gm                              */
#define SEC_0137_DEMO                       ((UINT32)(    137)) /*demo                            */
#define SEC_0138_CRUN                       ((UINT32)(    138)) /*crun                            */
#define SEC_0139_MAIN                       ((UINT32)(    139)) /*main                            */
#define SEC_0140_CTRANS                     ((UINT32)(    140)) /*ctrans                          */
#define SEC_0141_CXFSNBD                    ((UINT32)(    141)) /*cxfsnbd                         */
#define SEC_0142_CXFSNBDC                   ((UINT32)(    142)) /*cxfsnbdc                        */
#define SEC_0143_XXXXX                      ((UINT32)(    143)) /*-- obsolete --                  */
#define SEC_0144_XXXXXXXXXXX                ((UINT32)(    144)) /*-- obsolete --                  */
#define SEC_0145_XXXXXXXXX                  ((UINT32)(    145)) /*-- obsolete --                  */
#define SEC_0146_CFLV                       ((UINT32)(    146)) /*cflv                            */
#define SEC_0147_CMP4                       ((UINT32)(    147)) /*cmp4                            */
#define SEC_0148_CEXPAT                     ((UINT32)(    148)) /*cexpat                          */
#define SEC_0149_CHTTP                      ((UINT32)(    149)) /*chttp                           */
#define SEC_0150_CDNS                       ((UINT32)(    150)) /*cdhs                            */
#define SEC_0151_NGX                        ((UINT32)(    151)) /*      --- for nginx ---         */
#define SEC_0152_EVENT                      ((UINT32)(    152)) /*      --- for nginx event ---   */
#define SEC_0153_REQ                        ((UINT32)(    153)) /* --- for http request trace --- */
#define SEC_0154_CCONNP                     ((UINT32)(    154)) /*cconnp                          */
#define SEC_0155_XXXXXXX                    ((UINT32)(    155)) /*-- obsolete --                  */
#define SEC_0156_CSSL                       ((UINT32)(    156)) /*cssl                            */
#define SEC_0157_CHTTPS                     ((UINT32)(    157)) /*chttps                          */
#define SEC_0158_XXXXXXXXX                  ((UINT32)(    158)) //*-- obsolete --                  */
#define SEC_0159_XXXXXXXX                   ((UINT32)(    159)) /*-- obsolete --                  */
#define SEC_0160_XXXXXX                     ((UINT32)(    160)) /*-- obsolete --                  */
#define SEC_0161_XXXXXXX                    ((UINT32)(    161)) /*-- obsolete --                  */
#define SEC_0162_XXXXXXXXXXX                ((UINT32)(    162)) /*-- obsolete --                  */
#define SEC_0163_XXXXXX                     ((UINT32)(    163)) /*-- obsolete --                  */
#define SEC_0164_XXXXX                      ((UINT32)(    164)) /*-- obsolete --                  */
#define SEC_0165_XXXXX                      ((UINT32)(    165)) /*-- obsolete --                  */
#define SEC_0166_XXXXX                      ((UINT32)(    166)) /*-- obsolete --                  */
#define SEC_0167_XXXX                       ((UINT32)(    167)) /*-- obsolete --                  */
#define SEC_0168_XXXXXXXX                   ((UINT32)(    168)) /*-- obsolete --                  */
#define SEC_0169_XXXXXXX                    ((UINT32)(    169)) /*-- obsolete --                  */
#define SEC_0170_CSHELL                     ((UINT32)(    170)) /*cshell                          */
#define SEC_0171_CACLTIME                   ((UINT32)(    171)) /*cacltime                        */
#define SEC_0172_CSTORECFG                  ((UINT32)(    172)) /*cstorecfg                       */
#define SEC_0173_CSTORE                     ((UINT32)(    173)) /*cstore                          */
#define SEC_0174_CMAGLEV                    ((UINT32)(    174)) /*cmaglev                         */
#define SEC_0175_CVENDOR                    ((UINT32)(    175)) /*cvendor                         */
#define SEC_0176_CNGX                       ((UINT32)(    176)) /*cngx                            */
#define SEC_0177_CCACHE                     ((UINT32)(    177)) /*ccache                          */
#define SEC_0178_CCALLBACK                  ((UINT32)(    178)) /*ccallback                       */
#define SEC_0179_CREFRESH                   ((UINT32)(    179)) /*crefresh                        */
#define SEC_0180_CDCNPQUE                   ((UINT32)(    180)) /*cdcnpque                        */
#define SEC_0181_CDCNPRB                    ((UINT32)(    181)) /*cdcnprb                         */
#define SEC_0182_CDC                        ((UINT32)(    182)) /*cdc                             */
#define SEC_0183_CDCPGB                     ((UINT32)(    183)) /*cdcpgb                          */
#define SEC_0184_CDCPGD                     ((UINT32)(    184)) /*cdcpgd                          */
#define SEC_0185_CDCPGRB                    ((UINT32)(    185)) /*cdcpgrb                         */
#define SEC_0186_CDCPGV                     ((UINT32)(    186)) /*cdcpgv                          */
#define SEC_0187_CDCDN                      ((UINT32)(    187)) /*cdcdn                           */
#define SEC_0188_CDCNPDEG                   ((UINT32)(    188)) /*cdcnpdeg                        */
#define SEC_0189_CMCNPDEG                   ((UINT32)(    189)) /*cmcnpdeg                        */
#define SEC_0190_CXFSNPMGR                  ((UINT32)(    190)) /*cxfsnpmgr                       */
#define SEC_0191_CXFSDN                     ((UINT32)(    191)) /*cxfsdn                          */
#define SEC_0192_CXFS                       ((UINT32)(    192)) /*cxfs                            */
#define SEC_0193_CXFSGW                     ((UINT32)(    193)) /*cxfsgw                          */
#define SEC_0194_CXFSHTTP                   ((UINT32)(    194)) /*cxfshttp                        */
#define SEC_0195_CXFSNPQUE                  ((UINT32)(    195)) /*cxfsnpque                       */
#define SEC_0196_CXFSNPDEL                  ((UINT32)(    196)) /*cxfsnpdel                       */
#define SEC_0197_CXFSNP                     ((UINT32)(    197)) /*cxfsnp                          */
#define SEC_0198_CXFSNPRB                   ((UINT32)(    198)) /*cxfsnprb                        */
#define SEC_0199_CXFSC                      ((UINT32)(    199)) /*cxfsc                           */
#define SEC_0200_CXFSHTTPS                  ((UINT32)(    200)) /*cxfshttps                       */
#define SEC_0201_CXFSPGB                    ((UINT32)(    201)) /*cxfspgb                         */
#define SEC_0202_CXFSPGD                    ((UINT32)(    202)) /*cxfspgd                         */
#define SEC_0203_CXFSPGV                    ((UINT32)(    203)) /*cxfspgv                         */
#define SEC_0204_CXFSPGRB                   ((UINT32)(    204)) /*cxfspgrb                        */
#define SEC_0205_CXFSCFG                    ((UINT32)(    205)) /*cxfscfg                         */
#define SEC_0206_CNBD                       ((UINT32)(    206)) /*cnbd                            */
#define SEC_0207_CDEQUEUE                   ((UINT32)(    207)) /*cdequeue                        */
#define SEC_0208_CFC                        ((UINT32)(    208)) /*cfc                             */
#define SEC_0209_CMMAP                      ((UINT32)(    209)) /*cmmap                           */
#define SEC_0210_CPGBITMAP                  ((UINT32)(    210)) /*cpgbitmap                       */
#define SEC_0211_CDIO                       ((UINT32)(    211)) /*cdio                            */
#define SEC_0212_CMSYNC                     ((UINT32)(    212)) /*cmsync                          */
#define SEC_0213_CXFSOP                     ((UINT32)(    213)) /*cxfsop                          */
#define SEC_NONE_END                        ((UINT32)(    214))
#endif/*_SEC_MACRO_INC*/
